name: Deploy to Heroku

on:
  push:
    branches:
      - main # Change this to 'master' if your main branch is called master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Ensure this matches the Node.js version in your package.json engines

      - name: Install dependencies
        run: npm install

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15 # Using a popular Heroku deployment action
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "YOUR_HEROKU_APP_NAME" # IMPORTANT: Replace with your actual Heroku app name
          heroku_email: "YOUR_HEROKU_EMAIL" # IMPORTANT: Replace with the email associated with your Heroku account
